-- Seed the curated symbol universe (docs/ARCHITECTURE.md: ~S&P 500 +
-- Nasdaq-100 + popular ETFs). Sources, as of 2026-07-14:
--   * S&P 500: Wikipedia "List of S&P 500 companies" (exchange taken from
--     each symbol's exchange link: nyse.com / nasdaq.com / cboe.com).
--   * Nasdaq-100: Wikipedia "List of NASDAQ-100 companies" (all NASDAQ);
--     only symbols not already in the S&P 500 add rows.
--   * ETFs: hand-curated popular list. ETF exchange values are best-effort;
--     nothing reads the column yet, so do not treat it as authoritative.
--
-- Index rebalances are handled by later migrations: additions upsert, and
-- removals set is_active = FALSE. Rows are never DELETEd -- candles_daily
-- and orders reference instruments(symbol).

-- Common stocks: S&P 500 plus Nasdaq-100-only symbols (518).
INSERT INTO instruments (symbol, name, exchange) VALUES
    ('A', 'Agilent Technologies', 'NYSE'),
    ('AAPL', 'Apple Inc.', 'NASDAQ'),
    ('ABBV', 'AbbVie', 'NYSE'),
    ('ABNB', 'Airbnb', 'NASDAQ'),
    ('ABT', 'Abbott Laboratories', 'NYSE'),
    ('ACGL', 'Arch Capital Group', 'NASDAQ'),
    ('ACN', 'Accenture', 'NYSE'),
    ('ADBE', 'Adobe Inc.', 'NASDAQ'),
    ('ADI', 'Analog Devices', 'NASDAQ'),
    ('ADM', 'Archer Daniels Midland', 'NYSE'),
    ('ADP', 'Automatic Data Processing', 'NASDAQ'),
    ('ADSK', 'Autodesk', 'NASDAQ'),
    ('AEE', 'Ameren', 'NYSE'),
    ('AEP', 'American Electric Power', 'NASDAQ'),
    ('AES', 'AES Corporation', 'NYSE'),
    ('AFL', 'Aflac', 'NYSE'),
    ('AIG', 'American International Group', 'NYSE'),
    ('AIZ', 'Assurant', 'NYSE'),
    ('AJG', 'Arthur J. Gallagher & Co.', 'NYSE'),
    ('AKAM', 'Akamai Technologies', 'NASDAQ'),
    ('ALAB', 'Astera Labs', 'NASDAQ'),
    ('ALB', 'Albemarle Corporation', 'NYSE'),
    ('ALGN', 'Align Technology', 'NASDAQ'),
    ('ALL', 'Allstate', 'NYSE'),
    ('ALLE', 'Allegion', 'NYSE'),
    ('ALNY', 'Alnylam Pharmaceuticals', 'NASDAQ'),
    ('AMAT', 'Applied Materials', 'NASDAQ'),
    ('AMCR', 'Amcor', 'NYSE'),
    ('AMD', 'Advanced Micro Devices', 'NASDAQ'),
    ('AME', 'Ametek', 'NYSE'),
    ('AMGN', 'Amgen', 'NASDAQ'),
    ('AMP', 'Ameriprise Financial', 'NYSE'),
    ('AMT', 'American Tower', 'NYSE'),
    ('AMZN', 'Amazon', 'NASDAQ'),
    ('ANET', 'Arista Networks', 'NYSE'),
    ('AON', 'Aon plc', 'NYSE'),
    ('AOS', 'A. O. Smith', 'NYSE'),
    ('APA', 'APA Corporation', 'NASDAQ'),
    ('APD', 'Air Products', 'NYSE'),
    ('APH', 'Amphenol', 'NYSE'),
    ('APO', 'Apollo Global Management', 'NYSE'),
    ('APP', 'AppLovin', 'NASDAQ'),
    ('APTV', 'Aptiv', 'NYSE'),
    ('ARE', 'Alexandria Real Estate Equities', 'NYSE'),
    ('ARES', 'Ares Management', 'NYSE'),
    ('ARM', 'Arm Holdings', 'NASDAQ'),
    ('ASML', 'ASML Holding', 'NASDAQ'),
    ('ATO', 'Atmos Energy', 'NYSE'),
    ('AVB', 'AvalonBay Communities', 'NYSE'),
    ('AVGO', 'Broadcom', 'NASDAQ'),
    ('AVY', 'Avery Dennison', 'NYSE'),
    ('AWK', 'American Water Works', 'NYSE'),
    ('AXON', 'Axon Enterprise', 'NASDAQ'),
    ('AXP', 'American Express', 'NYSE'),
    ('AZO', 'AutoZone', 'NYSE'),
    ('BA', 'Boeing', 'NYSE'),
    ('BAC', 'Bank of America', 'NYSE'),
    ('BALL', 'Ball Corporation', 'NYSE'),
    ('BAX', 'Baxter International', 'NYSE'),
    ('BBY', 'Best Buy', 'NYSE'),
    ('BDX', 'Becton Dickinson', 'NYSE'),
    ('BEN', 'Franklin Resources', 'NYSE'),
    ('BF.B', 'Brown–Forman', 'NYSE'),
    ('BG', 'Bunge Global', 'NYSE'),
    ('BIIB', 'Biogen', 'NASDAQ'),
    ('BKNG', 'Booking Holdings', 'NASDAQ'),
    ('BKR', 'Baker Hughes', 'NASDAQ'),
    ('BLDR', 'Builders FirstSource', 'NYSE'),
    ('BLK', 'BlackRock', 'NYSE'),
    ('BMY', 'Bristol Myers Squibb', 'NYSE'),
    ('BNY', 'BNY Mellon', 'NYSE'),
    ('BR', 'Broadridge Financial Solutions', 'NYSE'),
    ('BRK.B', 'Berkshire Hathaway', 'NYSE'),
    ('BRO', 'Brown & Brown', 'NYSE'),
    ('BSX', 'Boston Scientific', 'NYSE'),
    ('BX', 'Blackstone Inc.', 'NYSE'),
    ('BXP', 'BXP, Inc.', 'NYSE'),
    ('C', 'Citigroup', 'NYSE'),
    ('CAH', 'Cardinal Health', 'NYSE'),
    ('CARR', 'Carrier Global', 'NYSE'),
    ('CASY', 'Casey''s', 'NASDAQ'),
    ('CAT', 'Caterpillar Inc.', 'NYSE'),
    ('CB', 'Chubb Limited', 'NYSE'),
    ('CBOE', 'Cboe Global Markets', 'CBOE'),
    ('CBRE', 'CBRE Group', 'NYSE'),
    ('CCEP', 'Coca-Cola Europacific Partners', 'NASDAQ'),
    ('CCI', 'Crown Castle', 'NYSE'),
    ('CCL', 'Carnival Corporation', 'NYSE'),
    ('CDNS', 'Cadence Design Systems', 'NASDAQ'),
    ('CDW', 'CDW Corporation', 'NASDAQ'),
    ('CEG', 'Constellation Energy', 'NASDAQ'),
    ('CF', 'CF Industries', 'NYSE'),
    ('CFG', 'Citizens Financial Group', 'NYSE'),
    ('CHD', 'Church & Dwight', 'NYSE'),
    ('CHRW', 'C.H. Robinson', 'NASDAQ'),
    ('CHTR', 'Charter Communications', 'NASDAQ'),
    ('CI', 'Cigna', 'NYSE'),
    ('CIEN', 'Ciena', 'NYSE'),
    ('CINF', 'Cincinnati Financial', 'NASDAQ'),
    ('CL', 'Colgate-Palmolive', 'NYSE'),
    ('CLX', 'Clorox', 'NYSE'),
    ('CMCSA', 'Comcast', 'NASDAQ'),
    ('CME', 'CME Group', 'NASDAQ'),
    ('CMG', 'Chipotle Mexican Grill', 'NYSE'),
    ('CMI', 'Cummins', 'NYSE'),
    ('CMS', 'CMS Energy', 'NYSE'),
    ('CNC', 'Centene Corporation', 'NYSE'),
    ('CNP', 'CenterPoint Energy', 'NYSE'),
    ('COF', 'Capital One', 'NYSE'),
    ('COHR', 'Coherent Corp.', 'NYSE'),
    ('COIN', 'Coinbase', 'NASDAQ'),
    ('COO', 'Cooper Companies (The)', 'NASDAQ'),
    ('COP', 'ConocoPhillips', 'NYSE'),
    ('COR', 'Cencora', 'NYSE'),
    ('COST', 'Costco', 'NASDAQ'),
    ('CPAY', 'Corpay', 'NYSE'),
    ('CPRT', 'Copart', 'NASDAQ'),
    ('CPT', 'Camden Property Trust', 'NYSE'),
    ('CRH', 'CRH plc', 'NYSE'),
    ('CRL', 'Charles River Laboratories', 'NYSE'),
    ('CRM', 'Salesforce', 'NYSE'),
    ('CRWD', 'CrowdStrike', 'NASDAQ'),
    ('CRWV', 'CoreWeave', 'NASDAQ'),
    ('CSCO', 'Cisco', 'NASDAQ'),
    ('CSGP', 'CoStar Group', 'NASDAQ'),
    ('CSX', 'CSX Corporation', 'NASDAQ'),
    ('CTAS', 'Cintas', 'NASDAQ'),
    ('CTSH', 'Cognizant', 'NASDAQ'),
    ('CTVA', 'Corteva', 'NYSE'),
    ('CVNA', 'Carvana', 'NYSE'),
    ('CVS', 'CVS Health', 'NYSE'),
    ('CVX', 'Chevron Corporation', 'NYSE'),
    ('D', 'Dominion Energy', 'NYSE'),
    ('DAL', 'Delta Air Lines', 'NYSE'),
    ('DASH', 'DoorDash', 'NASDAQ'),
    ('DD', 'DuPont', 'NYSE'),
    ('DDOG', 'Datadog', 'NASDAQ'),
    ('DE', 'Deere & Company', 'NYSE'),
    ('DECK', 'Deckers Brands', 'NYSE'),
    ('DELL', 'Dell Technologies', 'NYSE'),
    ('DG', 'Dollar General', 'NYSE'),
    ('DGX', 'Quest Diagnostics', 'NYSE'),
    ('DHI', 'D. R. Horton', 'NYSE'),
    ('DHR', 'Danaher Corporation', 'NYSE'),
    ('DIS', 'Walt Disney Company (The)', 'NYSE'),
    ('DLR', 'Digital Realty', 'NYSE'),
    ('DLTR', 'Dollar Tree', 'NASDAQ'),
    ('DOC', 'Healthpeak Properties', 'NYSE'),
    ('DOV', 'Dover Corporation', 'NYSE'),
    ('DOW', 'Dow Inc.', 'NYSE'),
    ('DPZ', 'Domino''s', 'NYSE'),
    ('DRI', 'Darden Restaurants', 'NYSE'),
    ('DTE', 'DTE Energy', 'NYSE'),
    ('DUK', 'Duke Energy', 'NYSE'),
    ('DVA', 'DaVita', 'NYSE'),
    ('DVN', 'Devon Energy', 'NYSE'),
    ('DXCM', 'Dexcom', 'NASDAQ'),
    ('EA', 'Electronic Arts', 'NASDAQ'),
    ('EBAY', 'eBay Inc.', 'NASDAQ'),
    ('ECHO', 'EchoStar', 'NASDAQ'),
    ('ECL', 'Ecolab', 'NYSE'),
    ('ED', 'Consolidated Edison', 'NYSE'),
    ('EFX', 'Equifax', 'NYSE'),
    ('EG', 'Everest Group', 'NYSE'),
    ('EIX', 'Edison International', 'NYSE'),
    ('EL', 'Estée Lauder Companies (The)', 'NYSE'),
    ('ELV', 'Elevance Health', 'NYSE'),
    ('EME', 'Emcor', 'NYSE'),
    ('EMR', 'Emerson Electric', 'NYSE'),
    ('EOG', 'EOG Resources', 'NYSE'),
    ('EQIX', 'Equinix', 'NASDAQ'),
    ('EQR', 'Equity Residential', 'NYSE'),
    ('EQT', 'EQT Corporation', 'NYSE'),
    ('ERIE', 'Erie Indemnity', 'NASDAQ'),
    ('ES', 'Eversource Energy', 'NYSE'),
    ('ESS', 'Essex Property Trust', 'NYSE'),
    ('ETN', 'Eaton Corporation', 'NYSE'),
    ('ETR', 'Entergy', 'NYSE'),
    ('EVRG', 'Evergy', 'NYSE'),
    ('EW', 'Edwards Lifesciences', 'NYSE'),
    ('EXC', 'Exelon', 'NASDAQ'),
    ('EXE', 'Expand Energy', 'NASDAQ'),
    ('EXPD', 'Expeditors International', 'NASDAQ'),
    ('EXPE', 'Expedia Group', 'NASDAQ'),
    ('EXR', 'Extra Space Storage', 'NYSE'),
    ('F', 'Ford Motor Company', 'NYSE'),
    ('FANG', 'Diamondback Energy', 'NASDAQ'),
    ('FAST', 'Fastenal', 'NASDAQ'),
    ('FCX', 'Freeport-McMoRan', 'NYSE'),
    ('FDS', 'FactSet', 'NYSE'),
    ('FDX', 'FedEx', 'NYSE'),
    ('FDXF', 'FedEx Freight', 'NYSE'),
    ('FE', 'FirstEnergy', 'NYSE'),
    ('FER', 'Ferrovial', 'NASDAQ'),
    ('FFIV', 'F5, Inc.', 'NASDAQ'),
    ('FICO', 'Fair Isaac', 'NYSE'),
    ('FIS', 'Fidelity National Information Services', 'NYSE'),
    ('FISV', 'Fiserv', 'NASDAQ'),
    ('FITB', 'Fifth Third Bancorp', 'NYSE'),
    ('FIX', 'Comfort Systems USA', 'NYSE'),
    ('FLEX', 'Flex Ltd.', 'NASDAQ'),
    ('FOX', 'Fox Corporation (Class B)', 'NASDAQ'),
    ('FOXA', 'Fox Corporation (Class A)', 'NASDAQ'),
    ('FRT', 'Federal Realty Investment Trust', 'NYSE'),
    ('FSLR', 'First Solar', 'NASDAQ'),
    ('FTNT', 'Fortinet', 'NASDAQ'),
    ('FTV', 'Fortive', 'NYSE'),
    ('GD', 'General Dynamics', 'NYSE'),
    ('GDDY', 'GoDaddy', 'NYSE'),
    ('GE', 'GE Aerospace', 'NYSE'),
    ('GEHC', 'GE HealthCare', 'NASDAQ'),
    ('GEN', 'Gen Digital', 'NASDAQ'),
    ('GEV', 'GE Vernova', 'NYSE'),
    ('GILD', 'Gilead Sciences', 'NASDAQ'),
    ('GIS', 'General Mills', 'NYSE'),
    ('GL', 'Globe Life', 'NYSE'),
    ('GLW', 'Corning Inc.', 'NYSE'),
    ('GM', 'General Motors', 'NYSE'),
    ('GNRC', 'Generac', 'NYSE'),
    ('GOOG', 'Alphabet Inc. (Class C)', 'NASDAQ'),
    ('GOOGL', 'Alphabet Inc. (Class A)', 'NASDAQ'),
    ('GPC', 'Genuine Parts Company', 'NYSE'),
    ('GPN', 'Global Payments', 'NYSE'),
    ('GRMN', 'Garmin', 'NYSE'),
    ('GS', 'Goldman Sachs', 'NYSE'),
    ('GWW', 'W. W. Grainger', 'NYSE'),
    ('HAL', 'Halliburton', 'NYSE'),
    ('HAS', 'Hasbro', 'NASDAQ'),
    ('HBAN', 'Huntington Bancshares', 'NASDAQ'),
    ('HCA', 'HCA Healthcare', 'NYSE'),
    ('HD', 'Home Depot (The)', 'NYSE'),
    ('HIG', 'Hartford (The)', 'NYSE'),
    ('HII', 'Huntington Ingalls Industries', 'NYSE'),
    ('HLT', 'Hilton Worldwide', 'NYSE'),
    ('HON', 'Honeywell Technologies', 'NASDAQ'),
    ('HONA', 'Honeywell Aerospace', 'NASDAQ'),
    ('HOOD', 'Robinhood Markets', 'NASDAQ'),
    ('HPE', 'Hewlett Packard Enterprise', 'NYSE'),
    ('HPQ', 'HP Inc.', 'NYSE'),
    ('HRL', 'Hormel Foods', 'NYSE'),
    ('HSIC', 'Henry Schein', 'NASDAQ'),
    ('HST', 'Host Hotels & Resorts', 'NASDAQ'),
    ('HSY', 'Hershey Company (The)', 'NYSE'),
    ('HUBB', 'Hubbell Incorporated', 'NYSE'),
    ('HUM', 'Humana', 'NYSE'),
    ('HWM', 'Howmet Aerospace', 'NYSE'),
    ('IBKR', 'Interactive Brokers', 'NASDAQ'),
    ('IBM', 'IBM', 'NYSE'),
    ('ICE', 'Intercontinental Exchange', 'NYSE'),
    ('IDXX', 'Idexx Laboratories', 'NASDAQ'),
    ('IEX', 'IDEX Corporation', 'NYSE'),
    ('IFF', 'International Flavors & Fragrances', 'NYSE'),
    ('INCY', 'Incyte', 'NASDAQ'),
    ('INTC', 'Intel', 'NASDAQ'),
    ('INTU', 'Intuit', 'NASDAQ'),
    ('INVH', 'Invitation Homes', 'NYSE'),
    ('IP', 'International Paper', 'NYSE'),
    ('IQV', 'IQVIA', 'NYSE'),
    ('IR', 'Ingersoll Rand', 'NYSE'),
    ('IRM', 'Iron Mountain', 'NYSE'),
    ('ISRG', 'Intuitive Surgical', 'NASDAQ'),
    ('IT', 'Gartner', 'NYSE'),
    ('ITW', 'Illinois Tool Works', 'NYSE'),
    ('IVZ', 'Invesco', 'NYSE'),
    ('J', 'Jacobs Solutions', 'NYSE'),
    ('JBHT', 'J.B. Hunt', 'NASDAQ'),
    ('JBL', 'Jabil', 'NYSE'),
    ('JCI', 'Johnson Controls', 'NYSE'),
    ('JKHY', 'Jack Henry & Associates', 'NASDAQ'),
    ('JNJ', 'Johnson & Johnson', 'NYSE'),
    ('JPM', 'JPMorgan Chase', 'NYSE'),
    ('KDP', 'Keurig Dr Pepper', 'NASDAQ'),
    ('KEY', 'KeyCorp', 'NYSE'),
    ('KEYS', 'Keysight Technologies', 'NYSE'),
    ('KHC', 'Kraft Heinz', 'NASDAQ'),
    ('KIM', 'Kimco Realty', 'NYSE'),
    ('KKR', 'KKR & Co.', 'NYSE'),
    ('KLAC', 'KLA Corporation', 'NASDAQ'),
    ('KMB', 'Kimberly-Clark', 'NASDAQ'),
    ('KMI', 'Kinder Morgan', 'NYSE'),
    ('KO', 'Coca-Cola Company (The)', 'NYSE'),
    ('KR', 'Kroger', 'NYSE'),
    ('KVUE', 'Kenvue', 'NYSE'),
    ('L', 'Loews Corporation', 'NYSE'),
    ('LDOS', 'Leidos', 'NYSE'),
    ('LEN', 'Lennar', 'NYSE'),
    ('LH', 'Labcorp', 'NYSE'),
    ('LHX', 'L3Harris', 'NYSE'),
    ('LII', 'Lennox International', 'NYSE'),
    ('LIN', 'Linde plc', 'NASDAQ'),
    ('LITE', 'Lumentum', 'NASDAQ'),
    ('LLY', 'Lilly (Eli)', 'NYSE'),
    ('LMT', 'Lockheed Martin', 'NYSE'),
    ('LNT', 'Alliant Energy', 'NASDAQ'),
    ('LOW', 'Lowe''s', 'NYSE'),
    ('LRCX', 'Lam Research', 'NASDAQ'),
    ('LULU', 'Lululemon Athletica', 'NASDAQ'),
    ('LUV', 'Southwest Airlines', 'NYSE'),
    ('LVS', 'Las Vegas Sands', 'NYSE'),
    ('LYB', 'LyondellBasell', 'NYSE'),
    ('LYV', 'Live Nation Entertainment', 'NYSE'),
    ('MA', 'Mastercard', 'NYSE'),
    ('MAA', 'Mid-America Apartment Communities', 'NYSE'),
    ('MAR', 'Marriott International', 'NASDAQ'),
    ('MAS', 'Masco', 'NYSE'),
    ('MCD', 'McDonald''s', 'NYSE'),
    ('MCHP', 'Microchip Technology', 'NASDAQ'),
    ('MCK', 'McKesson Corporation', 'NYSE'),
    ('MCO', 'Moody''s Corporation', 'NYSE'),
    ('MDLZ', 'Mondelez International', 'NASDAQ'),
    ('MDT', 'Medtronic', 'NYSE'),
    ('MELI', 'Mercado Libre', 'NASDAQ'),
    ('MET', 'MetLife', 'NYSE'),
    ('META', 'Meta Platforms', 'NASDAQ'),
    ('MGM', 'MGM Resorts', 'NYSE'),
    ('MKC', 'McCormick & Company', 'NYSE'),
    ('MLM', 'Martin Marietta Materials', 'NYSE'),
    ('MMM', '3M', 'NYSE'),
    ('MNST', 'Monster Beverage', 'NASDAQ'),
    ('MO', 'Altria', 'NYSE'),
    ('MOS', 'Mosaic Company (The)', 'NYSE'),
    ('MPC', 'Marathon Petroleum', 'NYSE'),
    ('MPWR', 'Monolithic Power Systems', 'NASDAQ'),
    ('MRK', 'Merck & Co.', 'NYSE'),
    ('MRNA', 'Moderna', 'NASDAQ'),
    ('MRSH', 'Marsh McLennan', 'NYSE'),
    ('MRVL', 'Marvell Technology', 'NASDAQ'),
    ('MS', 'Morgan Stanley', 'NYSE'),
    ('MSCI', 'MSCI Inc.', 'NYSE'),
    ('MSFT', 'Microsoft', 'NASDAQ'),
    ('MSI', 'Motorola Solutions', 'NYSE'),
    ('MSTR', 'MicroStrategy', 'NASDAQ'),
    ('MTB', 'M&T Bank', 'NYSE'),
    ('MTD', 'Mettler Toledo', 'NYSE'),
    ('MU', 'Micron Technology', 'NASDAQ'),
    ('NBIS', 'Nebius Group', 'NASDAQ'),
    ('NCLH', 'Norwegian Cruise Line Holdings', 'NYSE'),
    ('NDAQ', 'Nasdaq, Inc.', 'NASDAQ'),
    ('NDSN', 'Nordson Corporation', 'NASDAQ'),
    ('NEE', 'NextEra Energy', 'NYSE'),
    ('NEM', 'Newmont', 'NYSE'),
    ('NFLX', 'Netflix', 'NASDAQ'),
    ('NI', 'NiSource', 'NYSE'),
    ('NKE', 'Nike, Inc.', 'NYSE'),
    ('NOC', 'Northrop Grumman', 'NYSE'),
    ('NOW', 'ServiceNow', 'NYSE'),
    ('NRG', 'NRG Energy', 'NYSE'),
    ('NSC', 'Norfolk Southern', 'NYSE'),
    ('NTAP', 'NetApp', 'NASDAQ'),
    ('NTRS', 'Northern Trust', 'NASDAQ'),
    ('NUE', 'Nucor', 'NYSE'),
    ('NVDA', 'Nvidia', 'NASDAQ'),
    ('NVR', 'NVR, Inc.', 'NYSE'),
    ('NWS', 'News Corp (Class B)', 'NASDAQ'),
    ('NWSA', 'News Corp (Class A)', 'NASDAQ'),
    ('NXPI', 'NXP Semiconductors', 'NASDAQ'),
    ('O', 'Realty Income', 'NYSE'),
    ('ODFL', 'Old Dominion', 'NASDAQ'),
    ('OKE', 'Oneok', 'NYSE'),
    ('OMC', 'Omnicom Group', 'NYSE'),
    ('ON', 'ON Semiconductor', 'NASDAQ'),
    ('ORCL', 'Oracle Corporation', 'NYSE'),
    ('ORLY', 'O’Reilly Automotive', 'NASDAQ'),
    ('OTIS', 'Otis Worldwide', 'NYSE'),
    ('OXY', 'Occidental Petroleum', 'NYSE'),
    ('PANW', 'Palo Alto Networks', 'NASDAQ'),
    ('PAYX', 'Paychex', 'NASDAQ'),
    ('PCAR', 'Paccar', 'NASDAQ'),
    ('PCG', 'PG&E Corporation', 'NYSE'),
    ('PDD', 'PDD Holdings', 'NASDAQ'),
    ('PEG', 'Public Service Enterprise Group', 'NYSE'),
    ('PEP', 'PepsiCo', 'NASDAQ'),
    ('PFE', 'Pfizer', 'NYSE'),
    ('PFG', 'Principal Financial Group', 'NASDAQ'),
    ('PG', 'Procter & Gamble', 'NYSE'),
    ('PGR', 'Progressive Corporation', 'NYSE'),
    ('PH', 'Parker Hannifin', 'NYSE'),
    ('PHM', 'PulteGroup', 'NYSE'),
    ('PKG', 'Packaging Corporation of America', 'NYSE'),
    ('PLD', 'Prologis', 'NYSE'),
    ('PLTR', 'Palantir Technologies', 'NASDAQ'),
    ('PM', 'Philip Morris International', 'NYSE'),
    ('PNC', 'PNC Financial Services', 'NYSE'),
    ('PNR', 'Pentair', 'NYSE'),
    ('PNW', 'Pinnacle West Capital', 'NYSE'),
    ('PODD', 'Insulet Corporation', 'NASDAQ'),
    ('PPG', 'PPG Industries', 'NYSE'),
    ('PPL', 'PPL Corporation', 'NYSE'),
    ('PRU', 'Prudential Financial', 'NYSE'),
    ('PSA', 'Public Storage', 'NYSE'),
    ('PSKY', 'Paramount Skydance Corporation', 'NASDAQ'),
    ('PSX', 'Phillips 66', 'NYSE'),
    ('PTC', 'PTC Inc.', 'NASDAQ'),
    ('PWR', 'Quanta Services', 'NYSE'),
    ('PYPL', 'PayPal', 'NASDAQ'),
    ('Q', 'Qnity Electronics', 'NYSE'),
    ('QCOM', 'Qualcomm', 'NASDAQ'),
    ('RCL', 'Royal Caribbean Group', 'NYSE'),
    ('REG', 'Regency Centers', 'NASDAQ'),
    ('REGN', 'Regeneron Pharmaceuticals', 'NASDAQ'),
    ('RF', 'Regions Financial Corporation', 'NYSE'),
    ('RJF', 'Raymond James Financial', 'NYSE'),
    ('RKLB', 'Rocket Lab', 'NASDAQ'),
    ('RL', 'Ralph Lauren Corporation', 'NYSE'),
    ('RMD', 'ResMed', 'NYSE'),
    ('ROK', 'Rockwell Automation', 'NYSE'),
    ('ROL', 'Rollins, Inc.', 'NYSE'),
    ('ROP', 'Roper Technologies', 'NASDAQ'),
    ('ROST', 'Ross Stores', 'NASDAQ'),
    ('RSG', 'Republic Services', 'NYSE'),
    ('RTX', 'RTX Corporation', 'NYSE'),
    ('RVTY', 'Revvity', 'NYSE'),
    ('SBAC', 'SBA Communications', 'NASDAQ'),
    ('SBUX', 'Starbucks', 'NASDAQ'),
    ('SCHW', 'Charles Schwab Corporation', 'NYSE'),
    ('SHOP', 'Shopify', 'NASDAQ'),
    ('SHW', 'Sherwin-Williams', 'NYSE'),
    ('SJM', 'J.M. Smucker Company (The)', 'NYSE'),
    ('SLB', 'Schlumberger', 'NYSE'),
    ('SMCI', 'Supermicro', 'NASDAQ'),
    ('SNA', 'Snap-on', 'NYSE'),
    ('SNDK', 'Sandisk', 'NASDAQ'),
    ('SNPS', 'Synopsys', 'NASDAQ'),
    ('SO', 'Southern Company', 'NYSE'),
    ('SOLV', 'Solventum', 'NYSE'),
    ('SPCX', 'SpaceX', 'NASDAQ'),
    ('SPG', 'Simon Property Group', 'NYSE'),
    ('SPGI', 'S&P Global', 'NYSE'),
    ('SRE', 'Sempra', 'NYSE'),
    ('STE', 'Steris', 'NYSE'),
    ('STLD', 'Steel Dynamics', 'NASDAQ'),
    ('STT', 'State Street Corporation', 'NYSE'),
    ('STX', 'Seagate Technology', 'NASDAQ'),
    ('STZ', 'Constellation Brands', 'NYSE'),
    ('SW', 'Smurfit Westrock', 'NYSE'),
    ('SWK', 'Stanley Black & Decker', 'NYSE'),
    ('SWKS', 'Skyworks Solutions', 'NASDAQ'),
    ('SYF', 'Synchrony Financial', 'NYSE'),
    ('SYK', 'Stryker Corporation', 'NYSE'),
    ('SYY', 'Sysco', 'NYSE'),
    ('T', 'AT&T', 'NYSE'),
    ('TAP', 'Molson Coors Beverage Company', 'NYSE'),
    ('TDG', 'TransDigm Group', 'NYSE'),
    ('TDY', 'Teledyne Technologies', 'NYSE'),
    ('TECH', 'Bio-Techne', 'NASDAQ'),
    ('TEL', 'TE Connectivity', 'NYSE'),
    ('TER', 'Teradyne', 'NASDAQ'),
    ('TFC', 'Truist Financial', 'NYSE'),
    ('TGT', 'Target Corporation', 'NYSE'),
    ('TJX', 'TJX Companies', 'NYSE'),
    ('TKO', 'TKO Group Holdings', 'NYSE'),
    ('TMO', 'Thermo Fisher Scientific', 'NYSE'),
    ('TMUS', 'T-Mobile US', 'NASDAQ'),
    ('TPL', 'Texas Pacific Land Corporation', 'NYSE'),
    ('TPR', 'Tapestry, Inc.', 'NYSE'),
    ('TRGP', 'Targa Resources', 'NYSE'),
    ('TRI', 'Thomson Reuters', 'NASDAQ'),
    ('TRMB', 'Trimble Inc.', 'NASDAQ'),
    ('TROW', 'T. Rowe Price', 'NASDAQ'),
    ('TRV', 'Travelers Companies (The)', 'NYSE'),
    ('TSCO', 'Tractor Supply', 'NASDAQ'),
    ('TSLA', 'Tesla, Inc.', 'NASDAQ'),
    ('TSN', 'Tyson Foods', 'NYSE'),
    ('TT', 'Trane Technologies', 'NYSE'),
    ('TTD', 'Trade Desk (The)', 'NASDAQ'),
    ('TTWO', 'Take-Two Interactive', 'NASDAQ'),
    ('TXN', 'Texas Instruments', 'NASDAQ'),
    ('TXT', 'Textron', 'NYSE'),
    ('TYL', 'Tyler Technologies', 'NYSE'),
    ('UAL', 'United Airlines Holdings', 'NASDAQ'),
    ('UBER', 'Uber', 'NYSE'),
    ('UDR', 'UDR, Inc.', 'NYSE'),
    ('UHS', 'Universal Health Services', 'NYSE'),
    ('ULTA', 'Ulta Beauty', 'NASDAQ'),
    ('UNH', 'UnitedHealth Group', 'NYSE'),
    ('UNP', 'Union Pacific Corporation', 'NYSE'),
    ('UPS', 'United Parcel Service', 'NYSE'),
    ('URI', 'United Rentals', 'NYSE'),
    ('USB', 'U.S. Bancorp', 'NYSE'),
    ('V', 'Visa Inc.', 'NYSE'),
    ('VEEV', 'Veeva Systems', 'NYSE'),
    ('VICI', 'Vici Properties', 'NYSE'),
    ('VLO', 'Valero Energy', 'NYSE'),
    ('VLTO', 'Veralto', 'NYSE'),
    ('VMC', 'Vulcan Materials Company', 'NYSE'),
    ('VRSK', 'Verisk Analytics', 'NASDAQ'),
    ('VRSN', 'Verisign', 'NASDAQ'),
    ('VRT', 'Vertiv', 'NYSE'),
    ('VRTX', 'Vertex Pharmaceuticals', 'NASDAQ'),
    ('VST', 'Vistra Corp.', 'NYSE'),
    ('VTR', 'Ventas', 'NYSE'),
    ('VTRS', 'Viatris', 'NASDAQ'),
    ('VZ', 'Verizon', 'NYSE'),
    ('WAB', 'Wabtec', 'NYSE'),
    ('WAT', 'Waters Corporation', 'NYSE'),
    ('WBD', 'Warner Bros. Discovery', 'NASDAQ'),
    ('WDAY', 'Workday, Inc.', 'NASDAQ'),
    ('WDC', 'Western Digital', 'NASDAQ'),
    ('WEC', 'WEC Energy Group', 'NYSE'),
    ('WELL', 'Welltower', 'NYSE'),
    ('WFC', 'Wells Fargo', 'NYSE'),
    ('WM', 'Waste Management', 'NYSE'),
    ('WMB', 'Williams Companies', 'NYSE'),
    ('WMT', 'Walmart', 'NASDAQ'),
    ('WRB', 'W. R. Berkley Corporation', 'NYSE'),
    ('WSM', 'Williams-Sonoma, Inc.', 'NYSE'),
    ('WST', 'West Pharmaceutical Services', 'NYSE'),
    ('WTW', 'Willis Towers Watson', 'NASDAQ'),
    ('WY', 'Weyerhaeuser', 'NYSE'),
    ('WYNN', 'Wynn Resorts', 'NASDAQ'),
    ('XEL', 'Xcel Energy', 'NASDAQ'),
    ('XOM', 'ExxonMobil', 'NYSE'),
    ('XYL', 'Xylem Inc.', 'NYSE'),
    ('XYZ', 'Block, Inc.', 'NYSE'),
    ('YUM', 'Yum! Brands', 'NYSE'),
    ('ZBH', 'Zimmer Biomet', 'NYSE'),
    ('ZBRA', 'Zebra Technologies', 'NASDAQ'),
    ('ZTS', 'Zoetis', 'NYSE')
ON CONFLICT (symbol) DO NOTHING;

-- Popular ETFs (61).
INSERT INTO instruments (symbol, name, exchange) VALUES
    ('SPY', 'SPDR S&P 500 ETF Trust', 'NYSEARCA'),
    ('VOO', 'Vanguard S&P 500 ETF', 'NYSEARCA'),
    ('IVV', 'iShares Core S&P 500 ETF', 'NYSEARCA'),
    ('VTI', 'Vanguard Total Stock Market ETF', 'NYSEARCA'),
    ('QQQ', 'Invesco QQQ Trust', 'NASDAQ'),
    ('DIA', 'SPDR Dow Jones Industrial Average ETF Trust', 'NYSEARCA'),
    ('IWM', 'iShares Russell 2000 ETF', 'NYSEARCA'),
    ('RSP', 'Invesco S&P 500 Equal Weight ETF', 'NYSEARCA'),
    ('MDY', 'SPDR S&P MidCap 400 ETF Trust', 'NYSEARCA'),
    ('EFA', 'iShares MSCI EAFE ETF', 'NYSEARCA'),
    ('IEFA', 'iShares Core MSCI EAFE ETF', 'BATS'),
    ('EEM', 'iShares MSCI Emerging Markets ETF', 'NYSEARCA'),
    ('IEMG', 'iShares Core MSCI Emerging Markets ETF', 'NYSEARCA'),
    ('VEA', 'Vanguard FTSE Developed Markets ETF', 'NYSEARCA'),
    ('VWO', 'Vanguard FTSE Emerging Markets ETF', 'NYSEARCA'),
    ('VXUS', 'Vanguard Total International Stock ETF', 'NASDAQ'),
    ('AGG', 'iShares Core U.S. Aggregate Bond ETF', 'NYSEARCA'),
    ('BND', 'Vanguard Total Bond Market ETF', 'NASDAQ'),
    ('TLT', 'iShares 20+ Year Treasury Bond ETF', 'NASDAQ'),
    ('IEF', 'iShares 7-10 Year Treasury Bond ETF', 'NASDAQ'),
    ('SHY', 'iShares 1-3 Year Treasury Bond ETF', 'NASDAQ'),
    ('LQD', 'iShares iBoxx $ Investment Grade Corporate Bond ETF', 'NYSEARCA'),
    ('HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF', 'NYSEARCA'),
    ('TIP', 'iShares TIPS Bond ETF', 'NYSEARCA'),
    ('GLD', 'SPDR Gold Shares', 'NYSEARCA'),
    ('IAU', 'iShares Gold Trust', 'NYSEARCA'),
    ('SLV', 'iShares Silver Trust', 'NYSEARCA'),
    ('USO', 'United States Oil Fund', 'NYSEARCA'),
    ('XLB', 'Materials Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLC', 'Communication Services Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLE', 'Energy Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLF', 'Financial Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLI', 'Industrial Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLK', 'Technology Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLP', 'Consumer Staples Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLRE', 'Real Estate Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLU', 'Utilities Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLV', 'Health Care Select Sector SPDR Fund', 'NYSEARCA'),
    ('XLY', 'Consumer Discretionary Select Sector SPDR Fund', 'NYSEARCA'),
    ('SMH', 'VanEck Semiconductor ETF', 'NASDAQ'),
    ('SOXX', 'iShares Semiconductor ETF', 'NASDAQ'),
    ('IBB', 'iShares Biotechnology ETF', 'NASDAQ'),
    ('XBI', 'SPDR S&P Biotech ETF', 'NYSEARCA'),
    ('KRE', 'SPDR S&P Regional Banking ETF', 'NYSEARCA'),
    ('GDX', 'VanEck Gold Miners ETF', 'NYSEARCA'),
    ('VNQ', 'Vanguard Real Estate ETF', 'NYSEARCA'),
    ('ARKK', 'ARK Innovation ETF', 'NYSEARCA'),
    ('BITO', 'ProShares Bitcoin Strategy ETF', 'NYSEARCA'),
    ('IBIT', 'iShares Bitcoin Trust ETF', 'NASDAQ'),
    ('JETS', 'U.S. Global Jets ETF', 'NYSEARCA'),
    ('SCHD', 'Schwab U.S. Dividend Equity ETF', 'NYSEARCA'),
    ('VIG', 'Vanguard Dividend Appreciation ETF', 'NYSEARCA'),
    ('VYM', 'Vanguard High Dividend Yield ETF', 'NYSEARCA'),
    ('VUG', 'Vanguard Growth ETF', 'NYSEARCA'),
    ('VTV', 'Vanguard Value ETF', 'NYSEARCA'),
    ('JEPI', 'JPMorgan Equity Premium Income ETF', 'NYSEARCA'),
    ('JEPQ', 'JPMorgan Nasdaq Equity Premium Income ETF', 'NASDAQ'),
    ('QYLD', 'Global X NASDAQ 100 Covered Call ETF', 'NASDAQ'),
    ('TQQQ', 'ProShares UltraPro QQQ', 'NASDAQ'),
    ('SQQQ', 'ProShares UltraPro Short QQQ', 'NASDAQ'),
    ('SOXL', 'Direxion Daily Semiconductor Bull 3X Shares', 'NYSEARCA')
ON CONFLICT (symbol) DO NOTHING;
